// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtxus6B-Ah_G3xUdva6ypIR5M3lEjtFR8',
    appId: '1:553353007950:android:fed01ec4db265f7691841f',
    messagingSenderId: '553353007950',
    projectId: 'we-chat-881f3',
    storageBucket: 'we-chat-881f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY6WRb9BEAvpcdHLjejt0kVz4yBCK4TOk',
    appId: '1:553353007950:ios:98824fcfb3a55e5291841f',
    messagingSenderId: '553353007950',
    projectId: 'we-chat-881f3',
    storageBucket: 'we-chat-881f3.appspot.com',
    androidClientId: '553353007950-rj0mk63q3855ujt07h6ga71s5r5u92o4.apps.googleusercontent.com',
    iosClientId: '553353007950-t84p1g1u8t8eccg3k082h70ddvnou6jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
